name: Test Workflow 2

on: [push, workflow_dispatch]

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Print working directory #steps name
        run: |
          pwd
          ls -a 
          echo $GITHUB_WORKSPACE

      - name: Checking Packages
        run: |
          node -v
          git --version

      - name: Checkout/Copy the run-code
        uses: actions/checkout@v6

      - name: Set up node environment
        uses: actions/setup-node@v6

      - name: Verify node & copy code 
        run: |
          node -v 
          ls -a 

#$GITHUB_WORKSPACE -> env variable